---
- hosts: localhost
  connection: local
  force_handlers: True

  roles:
    - role: consensys.hyperledger_besu
      vars:
        ansible_python_interpreter: /usr/bin/python3
        besu_version: 21.1.4
        besu_network: palm
        besu_data_dir: "/data"
        besu_sync_mode: "FULL"
        besu_rpc_http_api: ["DEBUG","NET","WEB3","ETH","ADMIN","IBFT","TRACE"]
        besu_genesis_path: /etc/besu/genesis.json
        besu_permissions_nodes_config_file: /etc/besu/permissions_config.toml
        besu_bootnodes: ["enode://9cccbaae702d477c5fd4d704a2d6f92a90005f62de980b11b0d042877bf759774cf7d68d358c59427622e87538bc46afa1195d6ac12cb153d6771461c1830d1b@54.243.108.56:30303","enode://d6518f4f318a172158cf73c3e615c4eb488efb14c20b4a2f13570bf01092573222cd6935599a80017512457fb7f229cf6562f9d038b5d0dc98db95074d4a98b3@18.235.247.31:30303"]
        besu_host_ip: PARAM_BESU_HOST_IP

    - role: undergreen.prometheus-node-exporter
      become: yes
      vars:
        ansible_python_interpreter: /usr/bin/python