---
- name: Update instance/s
  hosts: all:!localhost
  remote_user: "ec2-user"
  gather_facts: True
  pre_tasks:
    - name: debug
      debug:
        var: remote_user
    - debug:
        var: ansible_ssh_private_key_file
    - debug:
        msg: besu_version
    - debug:
        msg: besu_network
    

  roles:
    - role: consensys.hyperledger_besu
    - role: undergreen.prometheus-node-exporter
      become: yes
